name: org_parser_example
description: Demonstrates how to use the org_parser plugin.
publish_to: 'none'
version: 0.0.1+0.0.1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.2
  shared_preferences: ^0.5.4
  provider: ^4.3.2
  http: ^0.12.0+2
  http_retry: ^0.1.1+3
  state_notifier: ^0.6.0
  flutter_state_notifier: ^0.6.1
  freezed_annotation:

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable:
  build_runner:
  freezed:

  org_parser:
    path: ../

flutter:
  uses-material-design: true
  assets:
    - assets/
