name: org_parser
description: org file parser for dart.
version: 1.0.0-dev
author: yuzumone
homepage: https://github.com/yuzumone/org_parser

environment:
  sdk: ">=2.1.0 <3.0.0"

dev_dependencies:
  test: ^1.6.0
  pedantic: ^1.8.0
