name: build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - name: pub get
        run: flutter pub get
      - run: echo "${{secrets.ANDROID_RELEASE_BASE64_KEY}}" | base64 -d > ./example/keystore.jks
      - run: echo "keyAlias=keystore" >> example/android/key.properties
      - run: echo "keyPassword=${{secrets.ANDROID_RELEASE_KEY_PASSWORD}}" >> example/android/key.properties
      - run: echo "storeFile=`pwd`/example/keystore.jks" >> example/android/key.properties
      - run: echo "storePassword=${{secrets.ANDROID_RELEASE_STORE_PASSWORD}}" >> example/android/key.properties
      - name: build apk
        run: cd example && flutter build apk --build-number ${GITHUB_RUN_NUMBER}
      - name: deploygate
        run: |
          curl \
          -H "Authorization: token ${{secrets.DEPLOYGATE_API_KEY}}" \
          -F "file=@example/build/app/outputs/flutter-apk/app-release.apk" \
          "https://deploygate.com/api/users/yuzumone/apps"
