name: test and lint

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - name: pub get
        run: dart pub get
      - name: format
        run: dart format --set-exit-if-changed .
      - name: analyze
        run: dart analyze lib
      - name: test
        run: dart test test
